### ISSUE TITLE
[Bug] Conflict with Quilt for use internal class for registering biome

### ISSUE THREAD

**Issue by SettingDust** [quiqueck/BCLib#2]
### What happened?

Need use api instead of internal class.
https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/api/biomes/BiomeAPI.java#L207
https://github.com/FabricMC/fabric/blob/1.19/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/NetherBiomes.java#L60=

https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/api/biomes/BiomeAPI.java#L237
https://github.com/FabricMC/fabric/blob/1.19/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/api/biome/v1/TheEndBiomes.java#L60=

### BCLib

git code

### Fabric API

0.55.1

### Minecraft

1.18.2 1.19

**Comment by quiqueck** [comment]
Thanks for reporting Quilt incompatibilities. 

I changed some uses, but there is still one class that currently uses the internal EndBiomeData to check what kind of end biome we have:
https://github.com/quiqueck/BCLib/blob/e850173d9e206b75272ed435cd904ea6d9223001/src/main/java/org/betterx/bclib/api/v2/generator/BCLibEndBiomeSource.java#L172

This will take me a bit to entangle, as it can not be replaced with the public API...

**Comment by lxly9** [comment]
Is there any date in sight for when quilt might be supported?

**Comment by quiqueck** [comment]
We need a way to determine where End-Biomes were intended to go (void or land). I created a PR in Fabric to address the issue in a supported manner (FabricMC/fabric#2369).

**Comment by quiqueck** [comment]
Should be fixed in 2.0.9

**Comment by faeldray** [comment]
This issue still exists on the 1.18.2 version of BCLib. Would it be possible to get a fix for that version as well?

**Comment by SettingDust** [comment]
> This issue still exists on the 1.18.2 version of BCLib. Would it be possible to get a fix for that version as well?

https://github.com/quiqueck/BCLib/commits/1.18.2-backported seems merged the fixes from 1.19. But haven't released

**Comment by quiqueck** [comment]
Our 1.18 releases do not support Quilt.
The Version you mentioned is incomplete and does not compile. It would need a significant time investment to get it running on 1.18.x.

**Comment by faeldray** [comment]
That's too bad but I understand. Thanks for responding!
